name: Test

on:
  - push
  - pull_request

jobs:
  test-or-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        registry-url: 'https://registry.npmjs.org'
    - name: Prepare
      run: npm ci
    - name: Report
      run: npx c8 report -a
